testing UNIT test should fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,3 +41,18 @@ jobs:
 
       - name: Running static analysis
         run: scons lint
+
+      - name: Running unit tests
+        run: scons test
+      
+      - name: Check test results
+        run: |
+          for log_file in build/unity_logs/*.txt; do
+            if grep -q 'FAIL' "$log_file"; then
+              echo "::error::Tests failed in $log_file. Check unity logs for details."
+              exit 1
+            fi
+            if grep -q 'IGNORE' "$log_file"; then
+              echo "::error::Tests ignored in $log_file. Check unity logs for details."
+            fi
+          done
